FROM quay.io/feedyard/circleci-remote-docker:5.1.0

LABEL maintainers = "nic.cheneweth@thoughtworks.com"

# most package versions unspecified - pull latest wherever possible
ENV HADOLINT_VERSION=1.16.3

# general packages to support building infra oriented docker images
RUN apk add --no-cache \
        docker \
        openrc \
        bash \
        curl \
        wget \
        python3 \
        ruby \
        ruby-bundler \
        ruby-bigdecimal \
        ruby-webrick \
        gnugp \
        jq && \
    apk add --virtual build-dependencies \
        build-base \
        python3-dev \
        ruby-dev \
        libffi-dev \
        musl-dev \
        g++ \
        gcc \
        make && \
    rc-update add docker boot && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    rm -r /root/.cache

RUN pip install \
        invoke \
        pylint \
        yamllint && \
    echo "gem: --no-document" > /etc/gemrc && \
    gem install \
        inspec-bin \
        rubocop && \
    wget -q https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64 && \
        chmod +x hadolint-Linux-x86_64 && \
        mv hadolint-Linux-x86_64 /usr/bin/hadolint && \
    gem cleanup && \
    rm -rf /usr/lib/ruby/gems/*/cache/* \
           /var/cache/apk/* \
           /tmp/* && \
    apk del build-dependencies

HEALTHCHECK NONE
