---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@0.1.0
  common: feedyard/common-pipeline-tasks@0.3.0

workflows:
  version: 2

  circleci-base-agent-executor-pipeline:
    jobs:
      - executor-tools/dev-release:
          context: executor-publishing
          image: feedyard/circleci-base-agent
          registry: quay.io
          after-build:
            - run:
                name: configuration testing
                command: |
                  set -euo pipefail
                  inspec exec --no-distinct-exit profiles/cis-docker
                  CID="$(docker run -it -d --entrypoint ash quay.io/feedyard/circleci-base-agent:$CIRCLE_SHA1)"
                  inspec exec profiles/circleci-base-agent/ -t docker://$CID
                  docker rm -f $CID
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - executor-tools/publish:
          context: executor-publishing
          image: feedyard/circleci-base-agent
          registry: quay.io
          after-publish:
            - common/slack:
                title: New Executor Version
                message: new version published feedyard/circleci-base-agent $CIRCLE_TAG
                webhook: $SLACK_WEBHOOK
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
